### ISSUE TITLE
Scan wifi issue

### ISSUE THREAD

**Issue by SagarRaiyani** [nickrussler/Android-Wifi-Hotspot-Manager-Class#10]
Hello,

I have working in wifi hostpot and i have test a this demo and i have some bug so please suggest me for this bug,

WifiApManager$1: java.net.SocketException: socket failed: EACCES (Permission denied)

this bug get in scan wifi hostpot in main.java 

Please suggest me.

**Comment by nickrussler** [comment]
You are probably missing a permission. Check out [this](http://stackoverflow.com/questions/11273197/error-message-java-net-socketexception-socket-failed-eacces-permission-denie) and [that](http://stackoverflow.com/questions/27687808/android-java-net-socketexceptionsocket-failed-eacces-permission-denied).

**Comment by SagarRaiyani** [comment]
i have also add this permission but issue is not fixed..

**Comment by nickrussler** [comment]
Can you give me some details about your environment? Device, Android Version etc.?

**Comment by SagarRaiyani** [comment]
i have use an android studio..

Devices is moto E 5.0.1 and samsung galaxy s3 neo  used



![capture](https://cloud.githubusercontent.com/assets/5584295/13226386/2fd21c1e-d9b7-11e5-8f2a-01fff83e6d51.PNG)

**Comment by nickrussler** [comment]
Maybe try to change `<permission ...></permission>` to `<uses-permission android:name="android.permission.INTERNET" />`

**Comment by SagarRaiyani** [comment]
thanks bro, solved..:)
