### ISSUE TITLE
Getting devices that are not only connected to hotspot but also available

### ISSUE THREAD

**Issue by ParagRKadam** [nickrussler/Android-Wifi-Hotspot-Manager-Class#16]
Very useful library thanks for it !
However I want to create a app which will display the list of all the devices which are within range of wifi hotspot, it may be connected or not. I simply want all the devices within the range of wifi hotspot.
Is this library capable of doing it? If yes how can i achieve it?

**Comment by nickrussler** [comment]
Hi, sorry but it is not possible.

**Comment by ParagRKadam** [comment]
Ok ,thanks for the reply. Sorry this is a bit out of scope but is there some other way of doing it? 
One thing i am sure is that it is possible because if the client device can know which wifi-routers/wifi-hotspot is available in its range ,this can only happen when the client device pings the wifi-hotspot device and in this process the wifi-hotspot would also be getting a list of which client devices are pinging it.
