### ISSUE TITLE
How to get capability of hotspot?

### ISSUE THREAD

**Issue by AbhiShah29** [nickrussler/Android-Wifi-Hotspot-Manager-Class#17]
Hi,
How can I get the security type(capability) of already created hotspot?
I am using mWifiHelper.getWifiApConfiguration().priority; to get it, but it gives me 0 only no matter its set as WPA,WPA2 or Open.
Can please tell me what I am doing wrong?

**Comment by nickrussler** [comment]
Hello @AbhiShah29,
this question does not seem to be specifically related to this library.
You can post this question to a general Q&A site such as [stackoverflow](https://stackoverflow.com/questions/ask).
